### ISSUE TITLE
Модификаторы элементов

### ISSUE THREAD

**Issue by unlok** [bem/bh#117]
Есть такие матчи (`bh 3.1.1`)
```js
module.exports = function(bh) {
    bh.match('block', function(ctx) {
        ctx.content({elem: 'elem1'});
    });
    bh.match('block__elem1_mod1', function() {
        // ...
    });
};
```

Такой шаблон дает ошибку:
```
TypeError: Cannot read property 'mod1' of undefined
```

Если изменить первый матч так, то все работает нормально:
```js
bh.match('block', function(ctx) {
    ctx.content({elem: 'elem1', mods: {}});
});
```

Я что-то делаю неправильно?

**Comment by zxqfox** [comment]
Похоже на баг, реально обновиться до 3.3.0? Хотя, врядли поможет, судя по ченжлогам.

**Comment by mishanga** [comment]
Это было поправлено в https://github.com/bem/bh/releases/tag/v3.1.3

**Comment by unlok** [comment]
Спасибо, обновился!
