### ISSUE TITLE
Add global matcher

### ISSUE THREAD

**Issue by dosyara** [bem/bh#121]
For extension purposes of BH-core functionality it wood be good to have API to set global matcher. This matcher must be executed on each BEMJSON-node to make necessary modifications.
As I understand, it's possible to want to execute some code before and after other user matchers. So, probably, we need ``beforeEach`` and ``afterEach`` kind of matchers.

**Comment by mishanga** [comment]
Предлагаемый синтаксис:
beforeEach: `bh.match('<'), function(ctx) { ... })`
afterEach: `bh.match('>'), function(ctx) { ... })`

**Comment by mishanga** [comment]
Второй вариант:
`bh.beforeEach(function(ctx) { ... })`
`bh.afterEach(function(ctx) { ... })`

**Comment by sameoldmadness** [comment]
Я за второй вариант. По нему можно догадаться, что происходит, не заглядывая в документацию.

**Comment by zxqfox** [comment]
Все-таки решились на это? ;-\

**Comment by tadatuta** [comment]
Предлагаю в этом месте сделать консистентно с BEMHTML:

```js
bh.match(function() {}, function() {});
```

смотреть в `typeof` первого аргумента и если там функция, выполнять шаблон только для кейсов, когда она возвращает truly-значение.

**Comment by dosyara** [comment]
Это же нельзя делать консистентно c BEMHTML, у шаблонизаторов разная "механика". У BH нет нигде подобного паттерна.

**Comment by tadatuta** [comment]
@dosyara 
Разве с точки зрения механики

```js
bh.match(function(ctx) {
    return ctx === 'bla';
}, function(ctx) { doSomething(); });`
```

чем-то отличается от

```js
bh.beforeEach(function(ctx) {
   if (ctx === 'bla') doSomething();
});
```
?

**Comment by zxqfox** [comment]
Там не все так просто, не получится смотреть в typeof.
Из этих матчеров собираются switch-case, и при добавлении матчера оно сбрасывает «кеш» собранных свичкейсов и пересобирает его при следующем вызове `apply`.

Т.е. ты прав, но этот function должен будет отрабатывать в switch-case, а с учетом того, что порядок играет — я не очень себе представляю, как это должно будет работать так, что результат был ожидаемым. Может я перебдел, конечно, но пока кажется, что это просто нереально.

Но даже если я не прав в предыдущем — то beforeEach — это последний матчер, afterEach — первый, но
- Не выйдет их доопределять (как гарантировать, что afterEach всегда будет вызываться?);
- Будут сложности со сборкой (как гарантировать, что beforeEach всегда будет последним?).

Пара проблем из тех, которые, кмк, не позволяют это сделать.

**Comment by mishanga** [comment]
@tadatuta @zxqfox все шаблоны перед запуском компилируются примерно в такую конструкцию:
```javascript
function applyMatchers(ctx, json) {
    subRes = _m1(ctx, json); // afterEach
    switch (json.block) {
       case "button":
           switch (json.elem) {
               case undefined:
                   subRes = _m0(ctx, json); // match('button')
           }
       }
    }         
    subRes = _m1(ctx, json); // afterEach
};
```
То есть там получается один большой switch, в который нельзя добавить глобальный шаблон. Можно только перед switch или после. Но для разных задач нужен разный порядок исполнения: где-то глобальный шаблон должен применяться до всех остальных, где-то после. Поэтому пришлось сделать явное разделение на beforeEach и afterEach.

**Comment by gruzzilkin** [comment]
А можно дополнить README с описанием и примером применения этой фичи? @zxqfox

**Comment by zxqfox** [comment]
@gruzzilkin Есть предложение что написать в ридми? ;)

**Comment by gruzzilkin** [comment]
@zxqfox Например, что данные методы можно использовать для преобразования входящего JSON в BEMJSON и последующим применением шаблонов bh. Т.е. по сути с помощью `beforeEach` можно делать то же самое, что и с помощью bemtree.

**Comment by mishanga** [comment]
Про это даже есть issue: #142
Но у меня руки не доходят.
