### ISSUE TITLE
Support nested mixes

### ISSUE THREAD

**Issue by tadatuta** [bem/bh#125]
Refer https://github.com/bem/bem-core/pull/874

**Comment by mishanga** [comment]
Одна из сильных сторон BH — в его консистентном поведении. Мне не нравятся изменения, ведущие к разрушению консистентности.
Насколько я понял, в bemhtml сделали частичное применение шаблонов — только по моде mix, но не по остальным модам.
Во-первых, это явное нарушение консистентности.
Во-вторых, в BH это можно реализовать только костылями.
Если уж смотреть в сторону применения шаблонов для миксов, то более глобально: #86 и #87
