### ISSUE TITLE
Support no-base css classes

### ISSUE THREAD

**Issue by mishanga** [bem/bh#132]
https://github.com/FrontenderMagazine/bem-sass-modifiers/blob/master/rus.md
```javascript
{ block: 'button', mods: { theme: 'red' }, elem: 'control', elemMods: { disabled: true } }
```
```html
<div class="button -theme-red _control -disabled"></div>
```

**Comment by tadatuta** [comment]
how could it coexist with `ctx.mix({ block: 'b1' });`?

**Comment by mishanga** [comment]
@tadatuta в честном БЭМ-мире — никак. Но есть много ребят, которые с этим готовы жить (см. ссылку выше).
Будет как-то так: `<div class="button -disabled clearfix"></div>`
Здесь действительно не ясно, к какому блоку относится модификатор. Но если это ограничение понимать, то можно с ним жить.

**Comment by zxqfox** [comment]
@tadatuta @mishanga Вы знаете, если это не сложно сделать, то я строго за ;-)
