### ISSUE TITLE
block vs. block_mod apply bug (order matters!)

### ISSUE THREAD

**Issue by 1999** [bem/bh#140]
BEMJSON
```javascript
{
    block: 'button',
    mods: {foo: true}
}
```

```javascript
bh.match('button_foo', function(ctx) {
   ctx.content('mod');
});

bh.match('button', function(ctx) {
   ctx.content('base');
});
```

Result HTML
```html
<div class="button button_foo">
base
</div>
```

Expected HTML
```html
<div class="button button_foo">
mod
</div>
```

**if you reorder bh.match() calls, everything works as expected.**

**Comment by 1999** [comment]
cc @megatolya

**Comment by zxqfox** [comment]
Compare this:
```css
.button_red { color: red }
.button { color: green }
```
with this:
```js
bh.match('button_red', function(ctx) { ctx.content('red'); });
bh.match('button', function(ctx) { ctx.content('green'); });
```

Button should be green. Okay?

**Comment by 1999** [comment]
@zxqfox let's assume that you have this bemjson: `{block: "button", mods: {red: true}}`. Then it shouldn't. Templates are applied from the most specific to the least one. In your case `button_red` template will be applied first and it will set content. Then `button` template should be applied, but content has already been set, so its content won't change.

**Comment by zxqfox** [comment]
@1999 Actually. It should even if you have `{block: "button", mods: {red: true}}`.

`.button_red`, as well as `bh.match('button_red'`, should go last to have the most weight.

```
.button { color: green }
.button_red { color: red }
```
`+`
```
bh.match('button', function(ctx) { ctx.content('green'); });
bh.match('button_red', function(ctx) { ctx.content('red'); });
```
`=`
Really red button modifier.

**Comment by 1999** [comment]
@zxqfox I'm not sure about this. Anyway @mishanga will help us.

**Comment by mishanga** [comment]
Я склоняюсь к тому, что это нормальное поведение: все подходящие шаблоны применяются в том порядке, в каком задекларированы (точнее, в обратном). Это аналогично поведению CSS. На мой взгляд, это понятное и ожидаемое поведение (если опять же проводить аналогию с CSS).
Кроме того, BEMHTML работает так же. Срабатывает тот шаблон, который задекларирован последним, независимо от наличия подпредиката про модификатор.
![2015-04-22_1618](https://cloud.githubusercontent.com/assets/521273/7275217/37ece6ba-e90b-11e4-8de2-77b330fd062b.png)

Won't fix.
