### ISSUE TITLE
Proposal: ctx.if()

### ISSUE THREAD

**Issue by Yeti-or** [bem/bh#157]
Добавить сахара:
вместо:
```
ctx
  .mix({ elem : 'control' })

if (ctx.mod('disabled') {
 ctx.attr('tabindex', -1)
} else {
 ctx.attr('title', 'yeah')
}
ctx.js(false)
```

писать что то типа такого:
```
ctx
  .mix({ elem : 'control' })
  .if(ctx.mod('disabled'), function(predicate) {
      if (predicate) {
        ctx.attr('tabindex', -1)
      else 
        ctx.attr('title', 'yeah')
  })
  .js(true)
```

**Comment by Yeti-or** [comment]
ради чейнинга всё

**Comment by megatolya** [comment]
кажется только нечитаеме станет)

**Comment by mishanga** [comment]
Мне тоже не нравится.

**Comment by zxqfox** [comment]
@mishanga Как на счет добавить сахара для расширения Ctx? Сейчас оно расширяется с помощью utils, который создается динамически, и все лежит в одном файле. Не думал про разнесение на три файла: сам BH, Ctx, и все, что связано с toHTML?

**Comment by mishanga** [comment]
Не вижу смысла усложнять всё.
Задача решается тривиально:
```
bh = new BH();
bh.utils.if = function(expr, fnTrue, fnFalse) {
    if (expr) fnTrue && fnTrue();
    else fnFalse && fnFalse();
    return this;
}
```
