### ISSUE TITLE
Bug with ctx.js()

### ISSUE THREAD

**Issue by arikon** [bem/bh#160]
```js
// ({block: 'block'})

bh.match('block', function(ctx) {
    ctx.js(false);
    ctx.js(true);
});

// <div class="block i-bem" data-bem='{"block":{}}'></div>
```

After the second call to `ctx.js(true)` the value of `js` is true. Should be `false`.

`js()` implementation in BH: https://github.com/bem/bh/blob/master/lib/bh.js#L437-L445
It seems that after the first call `json.js` stays `undefined`.
On the second call this happens: `this.extend(undefined, true)`
And then returns this: https://github.com/bem/bh/blob/master/lib/bh.js#L92

**Comment by zxqfox** [comment]
`this.ctx.js = force ?` → `this.ctx.js = force || this.ctx.js === undefined ?`
+ specs?

**Comment by arikon** [comment]
@mishanga Thanks!

**Comment by arikon** [comment]
@mishanga А в `bh 3.x` есть такая ошибка? Если да, то мы не сможем из `islands` оторвать костылик про это.

**Comment by mishanga** [comment]
@arikon да, выпустил 3.3.1

**Comment by arikon** [comment]
@mishanga Спасибо!

**Comment by mishanga** [comment]
@arikon блин, не так сделал. Выпущу пакет bh-3x с этим фиксом.
